### ISSUE TITLE
max mempool cost at 110 billion for mainnet

### ISSUE THREAD

**Issue by Anarkoic** [Chia-Network/pub-metrics-grafana#119]
should be 11 billion, yes?
![Screenshot from 2024-12-02 18-30-00](https://github.com/user-attachments/assets/07712084-e59a-4b04-a244-a58ce719ed97)

**Comment by hoffmang9** [comment]
I believe that is showing max mempool cost for the current limited block fill and that it auto updates as new chia-blockchain comes out.

**Comment by BrandtH22** [comment]
That is correct, the mac mempool is 10x the size of a block so this is current. The  70% block limit is the current cap set by the chia client
